server:
   port: 8088
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: event.sink
          group: order
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest